#Imagen modelo
FROM eclipse-temurin:17-jdk-jammy


ARG JAR_FILE=target/todo-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} todo.jar
#INFORMAR EL PUERTO EN DONDE SE EJECUTE EL CONTENEDOR(INFORMATIVO)
EXPOSE 8080
# LEVANTAR NUESTRA APLICACION CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java", "-jar", "todo.jar"]

